[tasks.base]
    templates = [
        [".spacemacs", "spacemacs/spacemacs"],
        [".gitconfig", "git/gitconfig"],
    ]
    links = [
        [".zshenv", "zshell/zshenv"],
        [".zshrc", "zshell/zshrc"],
        [".zsh.d/path.zshenv", "zshell/path.zshenv"],

        [".zsh-custom", "zshell/custom"],

        [".zsh.d/fzf.zshenv", "fzf/fzf.zshenv"],
        [".zsh.d/fzf.zsh", "fzf/fzf.zsh"],
        [".zsh.d/fzf_bindings.zsh", "fzf/fzf_bindings.zsh"],

        [".zsh.d/go.zshenv", "go/go.zshenv"],

        [".zsh.d/kube.zshenv", "kube/kube.zshenv"],

        [".config/nvim/init.vim", "nvim/init.vim"],
        [".config/nvim/autoload/plug.vim", "nvim/autoload/plug.vim"],

        [".zsh.d/rust.zshenv", "rust/rust.zshenv"],
    ]

[tasks.desktop]
    deps = ["base"]
    templates = [
        [".xinitrc", "x/xinitrc"],
        [".Xresources", "x/Xresources"],

        [".config/i3/config", "i3/config"],
        [".i3blocks.conf", "i3/i3blocks.conf"],

        [".config/dunst/dunstrc", "dunst/dunstrc"],

        [".config/alacritty/alacritty.yml", "alacritty/alacritty.yml"],
    ]
    cmds_post = [
        ["chmod", "755", ".xinitrc"],
    ]

[tasks.macos]
    deps = ["base"]
    links = [
        ["Library/KeyBindings/DefaultKeyBinding.dict", "macos/DefaultKeyBinding.dict"],
    ]

[tasks.nm]
    deps = ["macos"]

[tasks.ace]
    deps = ["desktop"]

[tasks.akame]
    deps = ["desktop"]

[tasks.fate]
    deps = ["desktop"]
