[tools]
"fnox" = "latest"
"go" = "latest"
"python" = "latest"
"rust" = ["stable", "nightly"]
"node" = "latest"
"bitwarden" = "latest"
"gcloud" = "latest"
"uv" = "latest"
"github:gotestyourself/gotestsum" = "latest"
"github:infisical/cli" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"pipx:mkdocs" = { version = "latest", uvx_args = "--with mkdocs-techdocs-core" }
