#!/bin/sh
#
# bootstrap installs things.

# Assume everyone's on OS X and run Homebrew (*nix-ers beware)
case "$(uname)" in
"Linux")
	if [ -f /etc/debian_release ]
	then
		. script/debian
	elif [ -f /etc/arch-release ]
	then
		. script/arch
	else
		echo "Unknown Linux"
	fi
	;;
"Darwin")
	. script/homebrew
	;;
*)
	echo "Unknown OS: $(uname)"
	;;
esac

# Run the install (I'd like to pull this out of rake, eventually)
rake install

# Manually run the sublime2 setup
echo "Running Sublime Text 2 Setup"
sublime2/setup
