#!/bin/sh
#
# bootstrap installs things.

# Assume everyone's on OS X and run Homebrew (*nix-ers beware)
case "$(uname)" in
"Linux")
	if [ -f /etc/debian_release ]
	then
        export DOTFILESENV=linux
        export DOTFILESDIST=debian
		. script/debian
    elif [ -f /etc/issue ] && grep -q Ubuntu /etc/issue
    then
        export DOTFILESENV=linux
        export DOTFILESDIST=ubuntu
        . script/debian
    elif [ -f /etc/issue ] && grep -q CrunchBang /etc/issue
    then
        export DOTFILESENV=linux
        export DOTFILESDIST=crunchbang
        . script/debian
	elif [ -f /etc/arch-release ]
	then
        export DOTFILESENV=linux
        export DOTFILESDIST=arch
		. script/arch
	else
        export DOTFILESENV=linux
        export DOTFILESDIST=unknown
		echo "Unknown Linux"
	fi
	;;
"Darwin")
    export DOTFILESENV=osx
    export DOTFILESDIST=osx
	. script/homebrew
	;;
*)
    export DOTFILESENV=unknown
    export DOTFILESDIST=unknown
	echo "Unknown OS: $(uname)"
	;;
esac

# Run the install (I'd like to pull this out of rake, eventually)
rake install

# Manually run the sublime2 setup
case "$DOTFILESENV" in
"linux")
  echo "Running Sublime Text 2 Setup (Linux)"
  sublime2/linux_setup
  ;;
"osx")
  echo "Running Sublime Text 2 Setup (OS X)"
  sublime2/osx_setup
  ;;
esac
