#!/bin/zsh

autoload -U colors && colors

git_prompt_info () {
 ref=$(env git symbolic-ref HEAD 2>/dev/null) || return
 echo "${ref#refs/heads/}"
}


git_dirty() {
  st=$(env git status 2>/dev/null | tail -n 1)
  if [[ $st == "" ]]
  then
    echo ""
  else
    if [[ $st == "nothing to commit (working directory clean)" || $st == "nothing to commit, working directory clean" ]]
    then
      echo "$fg_bold[green]$(git_prompt_info)$reset_color"
    else
      echo "$fg_bold[red]$(git_prompt_info)$reset_color"
    fi
  fi
}

for GD in `ls -1d */`
do
	cd $GD
	echo "$GD: $(git_dirty)"
	cd ..
done
