<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Kamailio/OpenSER</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*\#!(SER|KAMAILIO|OPENSER|MAXCOMPAT|ALL)\s*$</string>
			<key>name</key>
			<string>constant.language.kamailio</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.other.kamailio</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\#!|!!)(define|def|ifdef|ifndef|endif|trydefine|trydef|redefine|redef)(\s*(.+))?\s*$</string>
			<key>name</key>
			<string>constant.other.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=|==|\&gt;|\&lt;|\&gt;=|\&lt;=|!=|=~|\+=|!|&amp;&amp;|&amp;|\|\||\||~|^|\&lt;\&lt;|\&gt;\&gt;|\+|-)</string>
			<key>name</key>
			<string>keyword.operator.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(not|and|or|mod|strlen|strempty|eq|ieq|ne|ine)\b</string>
			<key>name</key>
			<string>keyword.operator.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(drop|exit|return|break|log|error)\b</string>
			<key>name</key>
			<string>keyword.control.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|switch|case|default|while)\b</string>
			<key>name</key>
			<string>keyword.control.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(forward|forward_tcp|forward_udp|forward_tls|forward_sctp)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(route|request_route|failure_route|reply_route|onreply_route|branch_route|onsend_route|event_route)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(exec|force_rport|add_rport|add_local_rport|force_tcp_alias|add_tcp_alias)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(udp_mtu|udp_mtu_try_proto|udp4_raw|udp4_raw_mtu|udp4_raw_ttl)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(setflag|resetflag|isflagset|flags|bool|setavpflag|resetavpflag|isavpflagset|avpflags)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(rewritehost|sethost|seth)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(rewritehostport|sethostport|sethp)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(rewritehostporttrans|sethostporttrans|sethpt)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(rewriteuser|setuser|setu)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(rewriteuserpass|setuserpass|setup)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(rewriteport|setport|setp)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(rewriteuri|seturi|reverturi)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(prefix|strip|strip_tail)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(userphone|remove|branch|clear_branches)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(set_advertised_address|set_advertised_port|force_send_socket)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(set_forward_no_connect|set_forward_close|set_reply_close)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cfg_select|cfg_reset)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(port|statistics|maxbuff|sql_buffer_size|children|socket_workers|async_workers|check_via|phone2tel)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(memlog|mem_log|memdbg|mem_dbg|mem_summary|mem_safety|mem_join)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(corelog|core_log)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(sip_warning|server_signature|server_header|user_agent_header|reply_to_via)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(user|uid|group|gid|chroot|workdir|wdir)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(mhomed|disable_tcp|tcp_children|tcp_accept_aliases|tcp_send_timeout|tcp_connect_timeout|tcp_connection_lifetime|tcp_poll_method|tcp_max_connections|tls_max_connections|tcp_no_connect|tcp_source_ipv4|tcp_source_ipv6|tcp_fd_cache|tcp_buf_write|tcp_async|tcp_conn_wq_max|tcp_wq_max|tcp_rd_buf_size|tcp_wq_blk_size|tcp_defer_accept|tcp_delayed_ack|scp_syncnt|tcp_linger2|tcp_keepalive|tcp_keepidle|tcp_keepintvl|tcp_keepcnt|tcp_crlf_ping|tcp_accept_no_cl|tcp_clone_rcvbuf)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(disable_tls|tls_disable|enable_tls|tls_enable|tlslog|tls_log|tls_port_no|tls_method|tls_verify|tls_require_certificate|tls_certificate|tls_private_key|tls_ca_list|tls_handshake_timeout|tls_send_timeout)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(disable_sctp|enable_sctp|sctp_children)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(advertised_address|advertised_port|disable_core_dump|open_files_limit|shm|shm_mem|shm_mem_size|shm_force_alloc|mlock_pages|real_time)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(real_time|rt_prio|rt_policy|rt_timer1_prio|rt_fast_timer_prio|rt_ftimer_prio|rt_timer1_policy|rt_ftimer_policy|rt_time2_prio|rt_stimer_prio|rt_timer2_policy|rt_stimer_policy)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(mcast_loopback|mcast_ttl|tos|pmtu_discovery|exit_timeout|ser_kill_timeout|max_while_loops|pv_buffer_size|pv_buffer_slots|http_reply_hack|http_reply_parse|version_table)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(server_id|max_recursive_level|max_branches|latency_log|latency_limit_db|latency_limit_action|msg_time|onsend_route_reply|description|descr|desc|loadmodule|loadpath|mpath|modparam)\b</string>
			<key>name</key>
			<string>support.function.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(method|uri|status|from_uri|to_uri|src_ip|src_port|dst_ip|dst_port|snd_ip|snd_port|snd_proto|to_proto|snd_af|to_af|to_ip|to_port|proto|af|myself|msg:len|\$\?|\$retcode|\$rc)</string>
			<key>name</key>
			<string>constant.language.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(debug|fork|fork_delay|modinit_delay)\b</string>
			<key>name</key>
			<string>support.variable.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(log_stderror|log_facility|log_name|log_color|log_prefix)\b</string>
			<key>name</key>
			<string>support.variable.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(listen|advertise|ADVERTISE|alias|auto_aliases)\b</string>
			<key>name</key>
			<string>support.variable.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(dns_cache_init|use_dns_cache|use_dns_failover|dns_cache_flags|dns_cache_negative_ttl|dns_cache_min_ttl|dns_cache_max_ttl|dns_cache_mem|dns_cache_gc_interval|dns_cache_del_nonexp|dns_cache_delete_nonexpired)\b</string>
			<key>name</key>
			<string>support.variable.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(dns|rev_dns|dns_try_ipv6|dns_try_naptr|dns_srv_lb|dns_srv_loadbalancing|dns_udp_pref|dns_udp_preference|dns_tcp_pref|dns_tcp_preference|dns_tls_pref|dns_tls_preference|dns_sctp_pref|dns_sctp_preference|dns_retr_time|dns_retr_no|dns_servers_no|dns_use_search_list|dns_search_full_match|dns_naptr_ignore_rfc)\b</string>
			<key>name</key>
			<string>support.variable.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(auto_bind_ipv6)\b</string>
			<key>name</key>
			<string>support.variable.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(dst_blacklist_init|use_dst_blacklist|dst_blacklist_mem|dst_blacklist_expire|dst_blacklist_ttl|dst_blacklist_gc_interval|dst_blacklist_udp_imask|dst_blacklist_tcp_imask|dst_blacklist_tls_imask|dst_blacklist_sctp_imask)\b</string>
			<key>name</key>
			<string>support.variable.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$(\w|\d|_)+</string>
			<key>name</key>
			<string>support.variable.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\".*\"</string>
			<key>name</key>
			<string>string.double.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((\#|//).*)$</string>
			<key>name</key>
			<string>comment.line.kamailio</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(yes|true|on|enable|no|false|off|disable)\b</string>
			<key>name</key>
			<string>constant.language.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(udp|UDP|tcp|TCP|tls|TLS|tctp|SCTP|ws|WS|wss|WSS|inet|INET|inet6|INET6)</string>
			<key>name</key>
			<string>constant.language.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(sslv23|SSLv23|SSLV23|sslv2|SSLv2|SSLV2|sslv3|SSLv3|SSLV3|tlsv1|TLSv1|TLSV1)</string>
			<key>name</key>
			<string>constant.language.kamailio</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\b</string>
			<key>name</key>
			<string>constant.numeric.kamailio</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.kamailio</string>
	<key>uuid</key>
	<string>6d498e7a-3b3e-4bf8-a37e-ca71ff372461</string>
</dict>
</plist>
