autoload -U compinit && compinit

# Oh My ZSH Settings
export ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM=$HOME/.zsh-custom
ZSH_THEME="aphistic"
plugins=(docker git kubectl)
source $ZSH/oh-my-zsh.sh

for config_file ($ZSHD/**/*.zsh) source $config_file

unsetopt correct
unsetopt SHARE_HISTORY

if [[ -a $HOME/.localrc ]]
then
  source $HOME/.localrc
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Fix TRAMP mode in emacs
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ '
